[workspace]
resolver = "2"
members = [
	"geo",
	"geoc",
	"render",
	"render-debug",
]

[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = true

[patch."https://github.com/SparkyPotato/hcomp"]
hcomp = { path = "../hcomp" }
