[package]
name = "render-debug"
authors = ["Synaptic Simulations"]
version = "0.1.0"
edition = "2021"

[dependencies]
pollster = "0.2"
env_logger = "0.9"
winit = "0.26"

render = { path = "../render" }
