[package]
name = "geo"
authors = ["Synaptic Simulations"]
version = "0.1.0"
edition = "2021"

[dependencies]
bitpacking = "0.8"
ctrlc = "3.2.2"
memmap2 = "0.5.3"
num_cpus = "1.13.1"
zstd = { version = "*", features = ["experimental", "zstdmt"] }
