[package]
name = "geoc"
authors = ["Synaptic Simulations"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
gdal = { version = "0.12.0", features = ["bindgen"] }
rayon = "1.5.3"

geo = { path = "../geo" }
